---
# For my dev environment only
version: "3"
services:
  repomanager:
    container_name: repomanager-dev
    image: repomanager
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env: devel
        fqdn: repomanager-dev.localhost
        max_upload_size: 64M
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - repomanager-dev-logs:/var/log/nginx
      - repomanager-dev-www:/var/www/repomanager
      - repomanager-dev-data:/var/lib/repomanager
      - repomanager-dev-repo:/home/repo

volumes:
  repomanager-dev-logs:
  repomanager-dev-www:
  repomanager-dev-data:
  repomanager-dev-repo: